#!/bin/bash

function start {
check
# Copying files
echo "Starting setup .."
sudo chmod +x script.sh
sudo /bin/bash script.sh
# Check if everything is good
check
}

function write {
#write static IP to dhcpcd.conf
echo "Writing static IP to dhcpcd.conf"
cat "installing" >> "/etc/dhcpcd.conf"
}

function end {
# Delete installing cache
echo "Cleaning up .."
sudo rm -rf /etc/backup-temp
echo "Added static IP"
}


function check {
#check if error, most cases its because of user privileges
if write; then
end
tput setaf 2; echo "..Please reboot the system before changes take effect"
else
tput setaf 1; echo "Write failed, permission errors?"
echo "Please use sudo command, sudo ./install"
fi
}

start


#uncomment the lane under to view the dhcpcd.conf
#sudo nano /etc/dhcpcd.conf
